# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Workflow - Pull Request Main (merge)

on:
  workflow_dispatch:
  merge_group:

env:
  RUST_VERSION: 1.85
  NODE_VERSION: 22
  REGISTRY: ghcr.io

jobs:
  env-expose:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exposing env vars..."
    outputs:
      rust-version: ${{ env.RUST_VERSION }}
      node-version: ${{ env.NODE_VERSION }}
      registry: ${{ env.REGISTRY }}

  build-cargo:
    needs: env-expose
    uses: ./.github/workflows/task-features.yaml
    with:
      rust-version: ${{ needs.env-expose.outputs.rust-version }}
    secrets: inherit

  build-nightly:
    needs: [env-expose, build-cargo]
    uses: ./.github/workflows/task-build-nightly.yaml
    with:
      registry: ${{ needs.env-expose.outputs.registry }}
      image-name: openrpc-testgen-runner
      image-file: ./runner.dockerfile
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    secrets: inherit
