# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Workflow - Pull Request Main

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  RUST_VERSION: 1.85
  NODE_VERSION: 22

jobs:
  env-expose:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exposing env vars..."
    outputs:
      rust-version: ${{ env.RUST_VERSION }}
      node-version: ${{ env.NODE_VERSION }}

  lint-cargo:
    needs: env-expose
    uses: ./.github/workflows/task-lint-cargo.yaml
    with:
      rust-version: ${{ needs.env-expose.outputs.rust-version }}
    secrets: inherit

  lint-prettier:
    needs: [env-expose, lint-cargo]
    uses: ./.github/workflows/task-lint-prettier.yaml
    with:
      node-version: ${{ needs.env-expose.outputs.node-version }}
    secrets: inherit

  build:
    needs: [env-expose, lint-prettier]
    uses: ./.github/workflows/task-build.yaml
    with:
      rust-version: ${{ needs.env-expose.outputs.rust-version }}
    secrets: inherit
