# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Task - Build And Publish Nightly Docker Image

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      registry:
        description: Container registry domain
        required: true
        type: string
      image-name:
        description: Name for the Docker image
        required: true
        type: string
      image-file:
        description: Dockerfile used to build the image
        required: true
        type: string

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build-nightly:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Tags
        id: tag
        run: |
          IMAGE="${{ inputs.registry }}/${{ github.repository_owner }}/${{ inputs.image-name }}"
          SHA=$(git rev-parse --short "$GITHUB_SHA")
          NIGHTLY="$IMAGE:nightly"
          NIGHTLY_SHA="$IMAGE:nightly-$SHA"

          echo "nightly=$NIGHTLY" >> $GITHUB_OUTPUT
          echo "nightly-sha=$NIGHTLY_SHA" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ${{ inputs.image-file }}
          tags: |
            ${{ steps.tag.outputs.nightly }}
            ${{ steps.tag.outputs.nightly-sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
