# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: Task - Build Project

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      rust-version:
        description: Rust version used for building
        required: true
        type: string

jobs:
  build-cargo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: ./.github/actions/setup-rust
        with:
          rust-version: ${{ inputs.rust-version }}

      - name: Build workspace
        run: |
          cargo build --all --all-features
